# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Docker Bamberg
email: ich@markusbenning.de
description: > # this means to ignore newlines until "baseurl:"
  Meet other developers and ops engineers using Docker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docker-bamberg.de" # the base hostname & protocol for your site
twitter_username: docker
github_username:  docker

# Build settings
markdown: kramdown
